name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.26

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          args: -E asciicheck -E bodyclose -E depguard -E dogsled -E dupl -E gochecknoinits -E goconst -E gocritic -E godot -E godox -E gofmt -E goimports -E golint -E gomodguard -E goprintffuncname -E interfacer -E maligned -E misspell -E nolintlint -E prealloc -E rowserrcheck -E stylecheck -E unconvert -E unparam -E whitespace -E wsl

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true
